import os
import json
from dotenv import load_dotenv
from anthropic import Anthropic
from ddgs import DDGS
from typing import TypedDict

load_dotenv()

client = Anthropic()
ddgs = DDGS()

# Step 1: Define the state (what data flows through the whole workflow)
class ResearchState(TypedDict):
    question: str          # the user's original question (set at start, never changes)
    queries: list[str]     # search queries generated by the planner
    raw_results: list[str] # search results collected by the researcher  
    findings: str          # structured summary produced by the synthesizer
    final_answer: str      # polished answer produced by the writer
    turn_count: int        # how many search turns the researcher has taken

def search_web(query: str) -> str:
    """Search the web and return formatted results."""
    results = ddgs.text(query, max_results=3)
    if not results:
        return f"No results found for: {query}"
    output = []
    for r in results:
        output.append(f"Title: {r['title']}\nURL: {r['href']}\nSnippet: {r['body']}\n")
    return "\n".join(output)

# Step 2: Define the planner node (takes question, returns search queries)
PLANNER_PROMPT = """You are a research planner. Given a question, generate a list of
specific search queries that will gather the information needed to answer it thoroughly.

Rules:
- Generate between 3 and 5 queries maximum
- Each query should targeta specific piece of information
- Queries should be concise and search-engine friendly
- Avoid redundant or overlapping queries"""

def planner_node(state: ResearchState) -> ResearchState:
    """Generate serach qeuries for the given question."""
    print(f"\n--- PLANNER ---")
    print(f"Question: {state['question']}")

    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=1024,
        system=PLANNER_PROMPT,
        messages=[
            {"role": "user", "content": f"Generate search queries to answer this question: {state['question']}"}
        ],
        tools=[
            {
                "name": "generate_queries",
                "description": "Generate a list of search queries",
                "input_schema": {
                    "type": "object",
                    "properties": {
                        "queries": {
                            "type": "array",
                            "items": {"type": "string"},
                            "description": "List of search queries to execute"
                        }
                    },
                    "required": ["queries"]
                }
            }
        ],
        tool_choice={"type": "tool", "name": "generate_queries"}
    )
    
    # Extract the structured output from the tool call
    tool_use_block = next(b for b in response.content if b.type == "tool_use")
    queries = tool_use_block.input["queries"]
    
    print(f"Generated {len(queries)} queries:")
    for i, q in enumerate(queries, 1):
        print(f"  {i}. {q}")
    
    state["queries"] = queries
    return state

# Step 3: Define the researcher node (takes queries, returns raw results)
def researcher_node(state: ResearchState) -> ResearchState:
    """Execute all search queries andcollect raw results."""
    print(f"\n--- RESEARCHER ---")
    print(f"Executing {len(state['queries'])} searches...")

    raw_results = []

    for i, query in enumerate(state['queries'], 1):
        print(f"  Searching ({i}/{len(state['queries'])}): {query}")
        result = search_web(query)
        raw_results.append(f"Query:  {query}\n\nResults:\n{result}")

    state['raw_results'] = raw_results
    state['turn_count'] = len(state['queries'])

    print(f"Collected {len(raw_results)} result sets")
    return state

# Step 4: Define the synthesizer node (takes raw results, returns structured findings)
SYNTHESIZER_PROMPT = """You are a research synthesizer. You will receive raw search results
from multiple queries. Your job is to distill them into clean, structured findings.

Your output should be organized, factual, and contain only information found in the results.
Do not add opinions or information not present in the results.

Format your findings with clear sections and bullet points so a writer can easily use them to produce a final answer."""

def synthesizer_node(state: ResearchState) -> ResearchState:
    """Synthesize raw search results into structured findings."""
    print(f"\n--- SYNTHESIZER ---")

    # Combine all raw results into one block for the LLM to process
    all_results = "\n\n---\n\n".join(state['raw_results'])

    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=4096,
        system=SYNTHESIZER_PROMPT,
        messages=[
            {
                "role": "user",
                "content": f"Question being researched: {state['question']}\n\nRaw search results:\n\n{all_results}"
            }
        ]
    )

    findings = response.content[0].text
    state['findings'] = findings
    
    print(f"Findings generated ({len(findings)} characters)")
    print(f"\nFindings preview:\n{findings[:400]}...")

    return state

# Step 5: Define the writer node (takes structured findings, returns final answer)
WRITER_PROMPT = """You are an expert wrtier who produces clear, engaging, and well-structured answers for readers.
You will receive structured research findings and a question.

Your job is write a comprehensive, readable final answer that:
- Directly addresses the question
- Uses the research findings as your source of truth
- Is well organized with headers and sections where appropriate
- Ends with a clear, actionable recommendation
- Feels like expert advice, not a data dump"""

def writer_node(state: ResearchState) -> ResearchState:
    """Write the final answer from structured findings."""
    print(f"\n--- WRITER ---")

    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=4096,
        system=WRITER_PROMPT,
        messages=[
            {
                "role": "user",
                "content": f"Question: {state['question']}\n\nResearch findings:\n\n{state['findings']}"
            }
        ]
    )

    final_answer = response.content[0].text
    state['final_answer'] = final_answer

    print(f"Final answer generated ({len(final_answer)} characters)")

    return state

# Step 6: Define the workflow (connect the nodes in order)

def run_workflow(question: str) -> str:
    """Run the complete research workflow."""
    print(f"\n{'='*60}")
    print(f"RESEARCH WORKFLOW")
    print(f"{'='*60}")

    # Initialize state
    state: ResearchState = {
        "question": question,
        "queries": [],
        "raw_results": [],
        "findings": "",
        "final_answer": "",
        "turn_count": 0
    }

    # Run nodes in sequence
    state = planner_node(state)
    state = researcher_node(state)
    state = synthesizer_node(state)
    state = writer_node(state)

    print(f"\n{'='*60}")
    print(f"WORKFLOW COMPLETE")
    print(f"  Queries executed: {state['turn_count']}")
    print(f"  Findings: {len(state['findings'])} characters")
    print(f"  Final answer: {len(state['final_answer'])} characters")
    print(f"{'='*60}")
    
    return state['final_answer']


# Step 7: Run it
if __name__ == "__main__":
    answer = run_workflow(
        "What are the pros and cons of living in NYC vs SF for a software engineer?"
    )
    print(f"\n{'='*60}")
    print("FINAL ANSWER")
    print(f"{'='*60}")
    print(answer)